import type { ProfileFormFieldDefinition } from "../schema/fieldTypes";

export const controlMaintenanceSectionFields: ProfileFormFieldDefinition[] = [
  {
    name: "maintenanceInterventions",
    label: "Maintenance interventions",
    section: "controlMaintenance",
    inputType: "repeater",
    appliesTo: ["all"],
    repeatable: true,
    children: [
      {
        name: "actionType",
        label: "Action type",
        section: "controlMaintenance",
        inputType: "radio",
        appliesTo: ["all"],
        options: [
          { value: "add", label: "Add" },
          { value: "remove", label: "Remove" },
        ],
      },
      {
        name: "resourceType",
        label: "Resource type",
        section: "controlMaintenance",
        inputType: "single_select",
        appliesTo: ["all"],
        options: [
          { value: "isolation", label: "Isolation" },
          { value: "light", label: "Light" },
          { value: "moisture", label: "Moisture" },
          { value: "heat", label: "Heat" },
          { value: "some_of_itself", label: "Some of itself" },
          { value: "building_blocks", label: "Building blocks" },
        ],
      },
      {
        name: "quantity",
        label: "Quantity",
        section: "controlMaintenance",
        inputType: "short_text",
        appliesTo: ["all"],
      },
      {
        name: "frequencyValue",
        label: "Frequency value",
        section: "controlMaintenance",
        inputType: "number",
        appliesTo: ["all"],
      },
      {
        name: "frequencyUnit",
        label: "Frequency unit",
        section: "controlMaintenance",
        inputType: "single_select",
        appliesTo: ["all"],
        options: [
          { value: "second", label: "Second" },
          { value: "minute", label: "Minute" },
          { value: "quarter_hour", label: "Quarter hour" },
          { value: "half_hour", label: "Half hour" },
          { value: "hour", label: "Hour" },
          { value: "day", label: "Day" },
          { value: "week", label: "Week" },
          { value: "fortnight", label: "Fortnight" },
          { value: "month", label: "Month" },
          { value: "quarter", label: "Quarter" },
          { value: "six_months", label: "6 months" },
          { value: "year", label: "Year" },
        ],
      },
      {
        name: "purpose",
        label: "Purpose",
        section: "controlMaintenance",
        inputType: "checkboxes",
        appliesTo: ["all"],
        options: [
          { value: "growth", label: "Growth" },
          { value: "healing", label: "Healing" },
          { value: "shaping", label: "Shaping" },
          { value: "cleaning", label: "Cleaning" },
          { value: "protection", label: "Protection" },
          { value: "pest_control", label: "Pest control" },
          { value: "threat_control", label: "Threat control" },
          { value: "reproduction", label: "Reproduction" },
          { value: "slowing_growth", label: "Slowing growth" },
          { value: "stopping_decay", label: "Stopping decay" },
          { value: "nutrient_support", label: "Nutrient support" },
          { value: "moisture_control", label: "Moisture control" },
          { value: "temperature_control", label: "Temperature control" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "purposeOther",
        label: "Other purpose",
        section: "controlMaintenance",
        inputType: "short_text",
        appliesTo: ["all"],
        showWhen: {
          field: "purpose",
          equals: "other",
        },
      },
      {
        name: "targetPart",
        label: "Target part",
        section: "controlMaintenance",
        inputType: "short_text",
        appliesTo: ["all"],
      },
      {
        name: "expectedOutcome",
        label: "Expected outcome",
        section: "controlMaintenance",
        inputType: "long_text",
        appliesTo: ["all"],
      },
      {
        name: "riskIfOverdone",
        label: "Risk if overdone",
        section: "controlMaintenance",
        inputType: "long_text",
        appliesTo: ["all"],
      },
      {
        name: "riskIfUnderdone",
        label: "Risk if underdone",
        section: "controlMaintenance",
        inputType: "long_text",
        appliesTo: ["all"],
      },
    ],
  },
];