import type { ProfileFormFieldDefinition } from "../schema/fieldTypes";

export const profileScopeSectionFields: ProfileFormFieldDefinition[] = [
  {
    name: "profileRecordType",
    label: "Profile record type",
    section: "profileScope",
    inputType: "single_select",
    appliesTo: ["all"],
    required: true,
    options: [
      { value: "item_profile", label: "Item profile" },
      { value: "plant_profile", label: "Plant profile" },
      { value: "plant_part_profile", label: "Plant part profile" },
      { value: "substrate_profile", label: "Substrate profile" },
      { value: "container_profile", label: "Container profile" },
      { value: "environment_profile", label: "Environment profile" },
      { value: "tool_profile", label: "Tool profile" },
      { value: "pest_threat_profile", label: "Pest / threat profile" },
    ],
  },
  {
    name: "profileIntention",
    label: "Profile intention",
    section: "profileScope",
    inputType: "checkboxes",
    appliesTo: ["all"],
    required: true,
    options: [
      { value: "identification", label: "Identification" },
      { value: "cultivation", label: "Cultivation" },
      { value: "diagnostics", label: "Diagnostics" },
      { value: "production", label: "Production" },
      { value: "inventory_reference", label: "Inventory reference" },
      { value: "ad_copy", label: "Ad copy" },
      { value: "greenhouse_planning", label: "Greenhouse planning" },
      { value: "sales", label: "Sales" },
      { value: "education", label: "Education" },
      { value: "research_notes", label: "Research notes" },
    ],
  },
  {
    name: "profileCompleteness",
    label: "Profile completeness",
    section: "profileScope",
    inputType: "radio",
    appliesTo: ["all"],
    required: true,
    options: [
      { value: "full", label: "Full" },
      { value: "partial", label: "Partial" },
      { value: "quick", label: "Quick" },
      { value: "update_only", label: "Update only" },
    ],
  },
  {
    name: "partBeingDescribed",
    label: "Part being described",
    section: "profileScope",
    inputType: "single_select",
    appliesTo: ["all"],
    required: true,
    options: [
      { value: "whole_item", label: "Whole item" },
      { value: "root", label: "Root" },
      { value: "stem_trunk", label: "Stem / trunk" },
      { value: "branch", label: "Branch" },
      { value: "leaf", label: "Leaf" },
      { value: "flower", label: "Flower" },
      { value: "fruit", label: "Fruit" },
      { value: "seed", label: "Seed" },
      { value: "bark", label: "Bark" },
      { value: "outer_skin", label: "Outer skin" },
      { value: "internal_flesh", label: "Internal flesh" },
      { value: "substrate", label: "Substrate" },
      { value: "container", label: "Container" },
      { value: "water", label: "Water" },
      { value: "environment_zone", label: "Environment zone" },
      { value: "other", label: "Other" },
    ],
  },
  {
    name: "partBeingDescribedOther",
    label: "Other part being described",
    section: "profileScope",
    inputType: "short_text",
    appliesTo: ["all"],
    showWhen: {
      field: "partBeingDescribed",
      equals: "other",
    },
  },
];